# gitlab-bash

include:
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/default/gitlab-default.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/default/gitlab-workflow.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/bash/shellcheck.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/bash/bash-test.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/docker/docker-login-build-push.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/gitlab/gitlab-check-tag.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/gitlab/gitlab-tag.yml'

stages:
  - build
  - pre-release
  - release

shellcheck:
  extends: .shellcheck
  stage: build

gitlab-check-tag:
  extends: .gitlab-check-tag
  stage: pre-release
  before_script:
    - source "$GITLAB_CI_SETUP"
    - GITLAB_TAG="$GITLAB_CI_VERSION"

gitlab-tag:
  extends: .gitlab-tag
  stage: release
  only:
    - master
  before_script:
    - source "$GITLAB_CI_SETUP"
    - GITLAB_TAG="$GITLAB_CI_VERSION"

docker-login-build-push:
  extends: .docker-login-build-push
  stage: release
  before_script:
    - source "$GITLAB_CI_SETUP"
    - DOCKER_IMAGE_REPOSITORY="$GITLAB_CI_GROUP"
    - DOCKER_IMAGE_NAME="$GITLAB_CI_NAME"
    - DOCKER_TAG="$GITLAB_RELEASE_VERSION"
