# gitlab-spring

include:
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/default/gitlab-default.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/default/gitlab-workflow.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/docker/docker-login-build-push.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/gitlab/gitlab-check-tag.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/maven/maven-clean-install.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/maven/maven-deploy.yml'
  - project: '<gitlab_project_path>/gitlab-ci'
    file: '/jobs/maven/maven-gitlab-tag.yml'

stages:
  - build
  - pre-release
  - release

maven-clean-install:
  extends: .maven-clean-install
  stage: build
  before_script:
    - source "$GITLAB_CI_SETUP"
    - MAVEN_RELEASE_VERSION="$GITLAB_RELEASE_VERSION"

gitlab-check-tag:
  extends: .gitlab-check-tag
  stage: pre-release
  before_script:
    - source "$GITLAB_CI_SETUP"
    - GITLAB_TAG="$GITLAB_CI_VERSION"

maven-gitlab-tag:
  extends: .maven-gitlab-tag
  stage: release
  only:
    - master
  before_script:
    - source "$GITLAB_CI_SETUP" 
    - MAVEN_RELEASE_VERSION="$GITLAB_CI_VERSION"

maven-deploy:
 extends: .maven-deploy
 stage: release
 before_script:
   - source "$GITLAB_CI_SETUP" 
   - MAVEN_RELEASE_VERSION="$GITLAB_RELEASE_VERSION"

docker-login-build-push:
  extends: .docker-login-build-push
  stage: release
  rules:
    - exists:
        - Dockerfile
  before_script:
    - source "$GITLAB_CI_SETUP"
    - DOCKER_IMAGE_REPOSITORY="$GITLAB_CI_GROUP"
    - DOCKER_IMAGE_NAME="$GITLAB_CI_NAME"
    - DOCKER_TAG="$GITLAB_RELEASE_VERSION"
