apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-job-configmap
  namespace: gitlab-runner
data:
  config.toml: |-
    concurrent = 4
    [[runners]]
      name = "gitlab-job"
      url = "https://<gitlab_base_url>/"
      token = "<token>"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        poll_timeout = 180
        pull_policy = "always"
        cpu_request = "1"
        service_cpu_request = "200m"